services:
  screenshot-bot:
    build: .
    image: valhalla:5000/screenshot-bot:latest
    container_name: screenshot-bot
    restart: always
    env_file: .env
    volumes:
      - ./data:/app/data
    labels:
      homepage.group: Bots
      homepage.name: Screenshot Bot
      homepage.icon: mdi-camera
      homepage.description: Discord
