version: '3'
services:
  screenshot-bot:
    container_name: screenshot-bot
    image: screenshot-bot:latest
    # ports:
    #   - "80:80"
    networks:
      slow-net:
        aliases:
          - screenshot-bot-slow-net
    environment:
      - TC_QDISC=netem
      - TC_DELAY=50ms
      - TC_RATE=1mbit
      - TC_CEIL=1mbit
networks:
  slow-net:
    driver: bridge
